
-- Explore All Objects in the Database

SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns in the Database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


--Find the date of the first and last order

SELECT
MIN(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the youngest and oldest customer

SELECT 
MIN(birthdate) AS oldest_birthdate,
MAX(birthdate) AS youngest_brithdate,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS oldest_customer,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS youngest_customer
FROM gold.dim_customers

--Find the total sales

SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

--Find how many items are sold

SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

--Find the average selling price

SELECT AVG(price) AS avg_price FROM gold.fact_sales

--Find the total number of orders

SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

--Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products

--Find the total number of customers
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales

--Generate a report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, SUM(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Orders' as measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Products' as measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Number of Customers' as measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers

--Find total customers by countries

SELECT 
country,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender

SELECT 
gender,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category

SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average cost in each categery

SELECT
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

--What is the total revenue generated for each category

SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--What is the total revenue generated by each customer?

SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--What is the distribution of items sold accros countries?

SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.cus tomer_key
GROUP BY
c.country
ORDER BY total_sold_items   DESC

--Which 5 products generate the highest revenue

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC


--What are the 5 worst-performing products in terms of sales

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

SELECT *
FROM(
	SELECT
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name) t
WHERE rank_products <= 5

